cookie:
  expiry_days: 30
  key: ${AUTH_SECRET_KEY}
  name: huoshui_auth
credentials:
  usernames:
    admin:
      email: admin@huoshui.ai
      name: Admin
      password: $2b$12$wsYnQM96Ju.FYd5ocfzZpeIepHeXefB8YMB4sVzA6c/qHPKqg4tES
    qpqqqwer:
      email: '931674'
      name: xingyu
      password: $2b$12$cFRp.qqaPafU9o86wgZjv.rPDryUZuVar0k9Um7vg4jTo8UavxYIe
